use log::debug;
use objc2_app_kit::NSPasteboard;

const SENSITIVE_PASTEBOARD_TYPES: &[&str] = &[
    // Standard pasteboard markers
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    "de.petermaurer.TransientPasteboardType",
    // 1Password
    "com.agilebits.onepassword",
    "com.agilebits.onepassword7",
    "com.agilebits.onepassword8",
    "ws.agile.1Password",
    // Other password managers
    "com.bitwarden.vault",
    "com.lastpass.lastpasspasswordmanager",
    "com.dashlane.dashlanephonefinal",
    "org.keepassxc.keepassxc",
    "com.callpod.keeper",
    "in.sinew.Enpass",
    "com.nordpass",
    "me.proton.pass",
    "com.phltech.strongbox",
    "com.siber.RoboForm",
    "com.mseven.msecure",
];

pub fn should_skip_content(pasteboard_types: &[String]) -> bool {
    if has_sensitive_pasteboard_type(pasteboard_types) {
        debug!("Skipping: password manager pasteboard type");
        return true;
    }
    false
}

pub fn get_pasteboard_types() -> Vec<String> {
    let pasteboard = NSPasteboard::generalPasteboard();
    pasteboard
        .types()
        .map(|types| types.iter().map(|t| t.to_string()).collect())
        .unwrap_or_default()
}

fn has_sensitive_pasteboard_type(pasteboard_types: &[String]) -> bool {
    pasteboard_types.iter().any(|pb_type| {
        SENSITIVE_PASTEBOARD_TYPES.iter().any(|sensitive| {
            pb_type == *sensitive || pb_type.starts_with(&format!("{}.", sensitive))
        })
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_password_manager_pasteboard_types() {
        assert!(should_skip_content(&[
            "org.nspasteboard.ConcealedType".to_string()
        ]));
        assert!(should_skip_content(&[
            "com.agilebits.onepassword".to_string()
        ]));
        assert!(should_skip_content(&["com.bitwarden.vault".to_string()]));
        assert!(should_skip_content(
            &["org.keepassxc.keepassxc".to_string()]
        ));
    }

    #[test]
    fn allows_normal_pasteboard_types() {
        assert!(!should_skip_content(
            &["public.utf8-plain-text".to_string()]
        ));
        assert!(!should_skip_content(&[
            "public.html".to_string(),
            "public.utf8-plain-text".to_string()
        ]));
    }

    #[test]
    fn allows_empty_pasteboard_types() {
        assert!(!should_skip_content(&[]));
    }
}
